version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - 127.0.0.1:49000:9000
      - 127.0.0.1:49443:9443
volumes:
  portainer_data:
